require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SectorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Sector. As you add validations to Sector, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:sector)
  }

  let(:invalid_attributes) {
    {
        :name => nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SectorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sectors as @sectors" do
      sector = Sector.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:sectors)).to eq([sector])
    end
  end

  describe "GET #show" do
    it "assigns the requested sector as @sector" do
      sector = Sector.create! valid_attributes
      get :show, params: {:id => sector.to_param}, session: valid_session
      expect(assigns(:sector)).to eq(sector)
    end
  end

  describe "GET #new" do
    it "assigns a new sector as @sector" do
      get :new, params: {}, session: valid_session
      expect(assigns(:sector)).to be_a_new(Sector)
    end
  end

  describe "GET #edit" do
    it "assigns the requested sector as @sector" do
      sector = Sector.create! valid_attributes
      get :edit, params: {:id => sector.to_param}, session: valid_session
      expect(assigns(:sector)).to eq(sector)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Sector" do
        expect {
          post :create, params: {:sector => valid_attributes}, session: valid_session
        }.to change(Sector, :count).by(1)
      end

      it "assigns a newly created sector as @sector" do
        post :create, params: {:sector => valid_attributes}, session: valid_session
        expect(assigns(:sector)).to be_a(Sector)
        expect(assigns(:sector)).to be_persisted
      end

      it "redirects to the created sector" do
        post :create, params: {:sector => valid_attributes}, session: valid_session
        expect(response).to redirect_to(Sector.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sector as @sector" do
        post :create, params: {:sector => invalid_attributes}, session: valid_session
        expect(assigns(:sector)).to be_a_new(Sector)
      end

      it "re-renders the 'new' template" do
        post :create, params: {:sector => invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            :name => 'New Name'
        }
      }

      it "updates the requested sector" do
        sector = Sector.create! valid_attributes
        put :update, params: {:id => sector.to_param, :sector => new_attributes}, session: valid_session
        sector.reload
        expect(sector.name).to eq('New Name')
      end

      it "assigns the requested sector as @sector" do
        sector = Sector.create! valid_attributes
        put :update, params: {:id => sector.to_param, :sector => valid_attributes}, session: valid_session
        expect(assigns(:sector)).to eq(sector)
      end

      it "redirects to the sector" do
        sector = Sector.create! valid_attributes
        put :update, params: {:id => sector.to_param, :sector => valid_attributes}, session: valid_session
        expect(response).to redirect_to(sector)
      end
    end

    context "with invalid params" do
      it "assigns the sector as @sector" do
        sector = Sector.create! valid_attributes
        put :update, params: {:id => sector.to_param, :sector => invalid_attributes}, session: valid_session
        expect(assigns(:sector)).to eq(sector)
      end

      it "re-renders the 'edit' template" do
        sector = Sector.create! valid_attributes
        put :update, params: {:id => sector.to_param, :sector => invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sector" do
      sector = Sector.create! valid_attributes
      expect {
        delete :destroy, params: {:id => sector.to_param}, session: valid_session
      }.to change(Sector, :count).by(-1)
    end

    it "redirects to the sectors list" do
      sector = Sector.create! valid_attributes
      delete :destroy, params: {:id => sector.to_param}, session: valid_session
      expect(response).to redirect_to(sectors_url)
    end
  end

end
